Repository Gomtori/do_bon, pull requests merged in 2023-01, with the labels that each got.

#13 feature/eslint-ts: apply the ts rules to eslint
  .eslintrc.json
  package-lock.json
  package.json
Labels: Frontend, refactor

#16 refactor: clean up nextjs samples
  pages/api/hello.ts
  pages/index.tsx
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
Labels: Frontend, refactor

#19 feat/DynamicComponent: add DynamicComponent for deferred loading
  modules/SignIn/index.tsx
  package-lock.json
  package.json
  pages/index.tsx
  util/DynamicComponent.tsx
Labels: feat, Frontend

#20 Feat/loading spinner
  components/LoadingSpinner.tsx
  pages/_app.tsx
  styles/globals.css
  tsconfig.json
  util/DynamicComponent.tsx
Labels: feat, Frontend

#21 Feat : Implement the SignIn layout
  components/LoadingSpinner.tsx
  components/TextInput.tsx
  constants/colorSet.ts
  modules/SignIn/SignInBox.tsx
  modules/SignIn/SignInWrapper.tsx
  modules/SignIn/index.tsx
  package-lock.json
  package.json
  styles/globals.css
Labels: feat, Frontend, design

#22 Feature/logo
  .eslintrc.json
  components/Logo/logo.tsx
  constants/mediaQuery.ts
  next.config.js
  package.json
  public/assets/logo.svg
  util/themeContextProvider.tsx
Labels: feat, Frontend, design
